### ISSUE TITLE
Need a note on naming conventions

### ISSUE THREAD

**Issue by dfenjves** [learn-co-curriculum/activerecord-migrations#6]
Something like:

**Note:** Naming files and classes correctly is _very_ important when using ActiveRecord. Use the following naming conventions when using ActiveRecord:
Class: Animal.rb
Table: create_table :animals
Migration: 01_create_animals.rb
Migration Class: class CreateAnimals

**Comment by deniznida** [comment]
@dfenjves added the naming conventions to readme
